# 数据库连接配置
DATABASE_IP:
DATABASE_NAME:
DATABASE_USERNAME:
DATABASE_PASSWORD:


# 消息队列配置
RABBITMQ_HOST:
RABBITMQ_USERNAME:
RABBITMQ_PASSWORD:

# Redis缓存配置
REDIS_HOST:

# 微信小程序配置
WX_APPLET_APPID:
WX_APPLET_APPSECRET:

# OSS相关配置信息
ALIYUN_OSS_ENDPOINT:
ALIYUN_OSS_DOWNLOAD_ENDPOINT:
ALIYUN_OSS_ACCESS_KEY_ID:
ALIYUN_OSS_ACCESS_KEY_SECRET:
ALIYUN_OSS_REGION:
ALIYUN_OSS_BUCKET:
ALIYUN_OSS_ROLE_ARN:
ALIYUN_OSS_ROLE_SESSION_NAME:

# API Client相关配置信息
API_CLIENT_APP_ID:
API_CLIENT_ACCESS_KEY:
API_CLIENT_SECRET_KEY:

