server:
  tomcat:
    uri-encoding: UTF-8
  port: 9001
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_IP}/${DATABASE_NAME}?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      statViewServlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: ${REDIS_HOST}
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10     # 连接池中的最大空闲连接
        min-idle: 5      # 连接池中的最小空闲连接
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: src/main/java
# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath*:mapper/xml/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.zhou.jianzhi.entity
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑为删除值
      id-type: auto

wx:
  applet:
    appid: ${WX_APPLET_APPID}
    appsecret: ${WX_APPLET_APPSECRET}


# OSS相关配置信息
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT}
    downloadEndPoint: ${ALIYUN_OSS_DOWNLOAD_ENDPOINT}
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
    region: ${ALIYUN_OSS_REGION}
    bucket: ${ALIYUN_OSS_BUCKET}
#    roleArn: ${ALIYUN_OSS_ROLE_ARN}
#    roleSessionName: ${ALIYUN_OSS_ROLE_SESSION_NAME}






